### ISSUE TITLE
tesseract.js 数据下载过慢

### ISSUE THREAD

**Issue by Enter-tainer** [winderica/DailyReport#3]
我目前的 workaround 是将[数据](https://github.com/naptha/tessdata/blob/gh-pages/4.0.0/eng.traineddata.gz)提前下载好，然后将

``` js
const worker = createWorker()
```

改为

``` js
const worker = createWorker({
  langPath: '.',
})
```

或许可以改成这样，然后在 README 里面说明一下。

如果可以的话，我去开一个 PR。

**Comment by winderica** [comment]
嗯，可以在配置文件`config.json`里提供本地数据集的可选字段，也欢迎 PR。

**Comment by ManiaciaChao** [comment]
挂代理下载或者换一个mirror，具体可以看我另一个issue

**Comment by winderica** [comment]
Fixed in 7d19dd2811221aad7dcb29143a15074255e7db9a.
