### ISSUE TITLE
tesseract的一些问题

### ISSUE THREAD

**Issue by ManiaciaChao** [winderica/DailyReport#4]
1. `tessedit_char_whitelist`在tesseract v4下是无效选项，需要使用v3。`worker.initialize("eng", OEM.TESSERACT_ONLY)` [#203](https://github.com/naptha/tesseract.js/issues/203)
2. `PSM.SINGLE_LINE`虽然不会出现换行，但是仍然会偶有识别出空格的情况。这种情况要处理一下。
3. 训练集不挂代理基本下载不下来，可以换一个url。腾讯云的cos可以白嫖50G，我把训练集放上去了。

```javascript
const worker = createWorker({
  langPath: "https://file-1252889006.cos.ap-guangzhou.myqcloud.com/tesseract",
});
await worker.load();
await worker.loadLanguage("eng");
await worker.initialize("eng", OEM.TESSERACT_ONLY);
await worker.setParameters({
  tessedit_pageseg_mode: PSM.SINGLE_LINE,
  tessedit_char_whitelist: "0123456789",
});
```

**Comment by ManiaciaChao** [comment]
顺便，单纯二值化+裁切之后ocr的成功率仍然很低，而HUSTPass似乎限制了最大尝试次数。我尚不清楚`execution: "e1s1"`这样的字段是否会被后端校验，也没去看这个错误尝试次数是在前端还是后端判断。所以我在`node-hustpass`中使用`ImageMagick`的`morphology`来去噪声，可以达到比较理想的识别率，但这样需要额外安装一个外部依赖。我想知道`sharp`中是否有对应的实现。另一个优化策略是和`libhustpass`一样判断连通量。

**Comment by winderica** [comment]
其实吧，它的验证码很简单，稍微观察下就可以发现每个数字都是一样的，完全没必要上OCR，根据像素匹配就行了。

问题是我懒的写（

**Comment by winderica** [comment]
Fixed in 7d19dd2811221aad7dcb29143a15074255e7db9a.
